### ISSUE TITLE
VBA compile error: Can't find project or library

### ISSUE THREAD

**Issue by danlester** [luozhijian/jupyterexcel#1]
Thank you for pointing me to your project!

I'm on a Mac and get this error when opening the xlsm file:

<img width="1607" alt="Screenshot 2019-07-11 at 10 01 45" src="https://user-images.githubusercontent.com/786238/61037533-2bc82d00-a3c3-11e9-9b58-22adbfd9eb54.png">

**Comment by luozhijian** [comment]
Thanks Dan.   I have not tested it in Mac.   Let me find one Mac and see what happened.   will keep you updated.

If you get a solution, please also let me know,

thanks,
Jim

________________________________

**Comment by luozhijian** [comment]
I am thinking to use https://github.com/VBA-tools/VBA-Web  to add web call support and remove dependency on windows Dictionary and WinHttpRequest.   will keep you updated.  thanks,

**Comment by danlester** [comment]
That's interesting, thanks for letting me know. However, for a project at this stage I don't think it is unreasonable just to say that Macs aren't supported for now. If most users are in the finance industry they are likely to be on Windows. If easy to fix for Macs then that's great too of course.

**Comment by luozhijian** [comment]
I added code from VBA-Web and I did quick test with a version of Macs Excel.  It works.  The excel file is uploaded, please let me know if you have any problem.

**Comment by danlester** [comment]
Thanks - this has definitely got past the error we were seeing with Mac Excel.

To be honest, I'm still struggling to get the plugin to work. With correct token and URL to TestingJupyter.ipynb the same as I have in my browser, I seem to just get the entire HTML of the notebook back into the Excel cell.

I'll keep trying!

**Comment by luozhijian** [comment]
Last night, the Google Cloud Platform, url is not working.  I changed it.   Please download the new excel and try one more time.  You should see the Excel with url to Google Cloud Platform working.  If you host in your localhost, please check the following:
1. The url which reference is http://34.67.24.96:8888/**Excel**/TestingJupyter.ipynb?token=ABCD      It is Excel, not notebooks.   With url starts with Excel, Jupyter know it should call JupyterExcel server extension to handle the url 
2. After you changed url, it is good that you close the excel and open again.  

Thanks Dan for trying.   I get this idea about 1 year ago in my previous job when using xlwings.  It took me couple months to figure out how to get it work.   I do not use it in current job.   So, my response will be a little slow.   thanks Jim

**Comment by danlester** [comment]
Thank you. The Google Cloud URL works fine (I hadn't tried it before) but I still can't get it to work locally I'm afraid. I just see:

[W 11:16:23.839 NotebookApp] 404 GET /Excel/TestingJupyter.ipynb?token=ABCD&functionname=set_variable_a&1=From%20Excel%202019-07-26%2011%3A16%3A24 (::1) 1.40ms referer=None

in the Jupyter logs.

Don't worry about it as I don't need to use it right now.
